---
- name: install glance packages
  yum: pkg={{ item }} state=present
  with_items:
    - nfs-utils
    - openstack-glance
    - openstack-utils
    - openstack-selinux
  tags: glance

- name: enable nfs support services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - rpcbind
    - nfslock
  when: default_store == 'file'
  tags: glance

- name: install rabbitmq driver
  yum: pkg=python-kombu state=present
  when: use_rabbit
  tags: glance

- name: deploy glance config files
  template: src={{ openstack_release }}/{{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=glance
  with_items:
    - { src: glance-registry.conf.j2, dest: /etc/glance/glance-registry.conf }
    - { src: glance-api.conf.j2, dest: /etc/glance/glance-api.conf }
  notify: restart glance
  tags: glance

- name: run db_sync for glance
  shell: runuser glance -s /bin/sh -c '/usr/bin/glance-manage db_sync'
  run_once: true
  tags: glance

- name: disable glance services
  service: name={{ item }} enabled=no
  with_items:
    - openstack-glance-registry
    - openstack-glance-api
  tags: glance

- name: create pacemaker cloned resources for glance-registry
  pcs_resource: command=create name=glance-registry type=systemd:openstack-glance-registry clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: ansible_distribution_major_version|int == 7
  tags: glance

- name: create pacemaker cloned resources for glance-registry
  pcs_resource: command=create name=glance-registry type=lsb:openstack-glance-registry clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: ansible_distribution_major_version|int == 6
  tags: glance

- name: create pacemaker cloned resources for glance-api
  pcs_resource: command=create name=glance-api type=systemd:openstack-glance-api clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: ansible_distribution_major_version|int == 7
  tags: glance

- name: create pacemaker cloned resources for glance-api
  pcs_resource: command=create name=glance-api type=lsb:openstack-glance-api clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: ansible_distribution_major_version|int == 6
  tags: glance

- name: create pacemaker constraint for glance
  shell: pcs constraint list --full | grep id:order-glance-registry-clone-glance-api-clone-mandatory || pcs constraint order start glance-registry-clone then glance-api-clone
  run_once: true
  tags: glance
