---
public_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + primary_if ].ipv4.address }}"
internal_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + private_if ].ipv4.address }}"
tunnel_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + tunnel_if ].ipv4.address }}"
neutron_bind_host: "{{ internal_ipaddr }}"
