---
- name: restart horizon
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - httpd
    - memcached

- name: restart httpd
  service: name=httpd state=restarted
