---
- name: install neutron packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-neutron
    - openstack-utils
    - openstack-selinux
    - openvswitch
  when: use_neutron
  tags: neutron

- name: install ml2 plugin
  yum: pkg=openstack-neutron-ml2 state=present
  when: use_neutron_ml2
  tags: neutron

- name: install openvswitch plugin
  yum: pkg=openstack-neutron-openvswitch state=present
  when: use_neutron_ovs
  tags: neutron

- name: install cisco plugin
  yum: pkg=openstack-neutron-cisco state=present
  when: use_neutron_cisco
  tags: neutron

- name: start openvswitch
  service: name=openvswitch enabled=yes state=started
  when: use_neutron
  tags: neutron

- name: get tenant services uuid
  shell: source /root/keystonerc_admin; keystone tenant-get services | awk '/id/ { print $4 }'
  register: tenant_services_uuid
  when: use_neutron
  tags: neutron

- name: deploy Havana specific Neutron config files
  template: src=havana/{{ item }}.j2
            dest=/etc/neutron/{{ item }}
            mode=0640 owner=root group=neutron
  with_items:
    - agent_watch.ini
    - api-paste.ini
  when: use_neutron and openstack_release == 'havana'
  tags: neutron

- name: set custom Neutron policy
  copy: src=files/neutron/policy.json
        dest=/etc/neutron/policy.json
        mode=0640 owner=root group=neutron
  when: use_neutron_custom_policy
  tags: neutron

- name: deploy the neutron.conf file
  template: src={{ openstack_release }}/neutron.conf.j2
            dest=/etc/neutron/neutron.conf
            mode=0640 owner=root group=neutron
  when: use_neutron
  tags: neutron

- name: deploy the metadata_agent.ini file
  template: src={{ openstack_release }}/metadata_agent.ini.j2
            dest=/etc/neutron/metadata_agent.ini
            mode=0640 owner=root group=neutron
  when: use_neutron
  tags: neutron

- name: deploy the dhcp_agent.ini file
  template: src={{ openstack_release }}/dhcp_agent.ini.j2
            dest=/etc/neutron/dhcp_agent.ini
            mode=0640 owner=root group=neutron
  when: use_neutron
  tags: neutron

- name: deploy the lbaas_agent.ini file
  template: src={{ openstack_release }}/lbaas_agent.ini.j2
            dest=/etc/neutron/lbaas_agent.ini
            mode=0640 owner=root group=neutron
  when: use_lbaas
  tags: neutron

- name: deploy the l3_agent.ini file
  template: src={{ openstack_release }}/l3_agent.ini.j2
            dest=/etc/neutron/l3_agent.ini
            mode=0640 owner=root group=neutron
  when: use_neutron
  tags: neutron

- name: deploy the ml2_conf.ini file
  template: src={{ openstack_release }}/ml2_conf.ini.j2
            dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            mode=0640 owner=root group=neutron
  when: use_neutron_ml2
  tags: neutron

- name: deploy the ovs_neutron_plugin.ini file
  template: src={{ openstack_release }}/ovs_neutron_plugin.ini.j2
            dest=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
            mode=0640 owner=root group=neutron
  when: use_neutron_ovs
  tags: neutron

- name: deploy the cisco_plugins.ini file
  template: src={{ openstack_release }}/cisco_plugins.ini.j2
            dest=/etc/neutron/plugins/cisco/cisco_plugins.ini
            mode=0640 owner=root group=neutron
  when: use_neutron_cisco
  tags: neutron

- name: link plugin.ini to the ml2 plugin config file
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link
  when: use_neutron_ml2
  tags: neutron

- name: link plugin.ini to the ovs plugin config file
  file: src=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini dest=/etc/neutron/plugin.ini state=link
  when: use_neutron_ovs and not use_neutron_ml2
  tags: neutron

- name: create integration bridge
  openvswitch_bridge: bridge=br-int state=present
  when: use_neutron
  tags: neutron

- name: create tunneling bridge
  openvswitch_bridge: bridge=br-tun state=present
  when: neutron_ovs_tunnel_type is defined
  tags: neutron

- name: create external network bridge
  openvswitch_bridge: bridge={{ neutron_external_network_bridge | default('br-ex') }} state=present
  when: use_neutron_l3
  tags: neutron

- name: create ovs bridges
  openvswitch_bridge: bridge={{ item.bridge }} state=present
  with_items: neutron_ovs_bridges
  when: neutron_ovs_bridges is defined
  tags: neutron

- name: configure ovs ports
  openvswitch_port: bridge={{ item.bridge }} port={{ item.port }} state=present
  with_items: neutron_ovs_bridges
  when: neutron_ovs_bridges is defined
  tags: neutron

- name: create a directory for the cisco nexus ssh keys
  file: dest=/var/lib/neutron/.ssh mode=0700 owner=neutron group=neutron state=directory
  when: use_neutron_cisco
  tags: neutron

- name: make cisco nexus switch ssh keys known
  copy: src=special/cisco_nexus.keys dest=/var/lib/neutron/.ssh/known_hosts mode=0644 owner=neutron group=neutron
  when: use_neutron_cisco
  tags: neutron

- name: stamp neutron database
  command: /usr/bin/neutron-db-manage --config-file /usr/share/neutron/neutron-dist.conf --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini stamp "{{ openstack_release }}"
  run_once: true
  tags: neutron

- name: disable neutron services
  service: name={{ item }} enabled=no 
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
  when: use_neutron and use_ha_controller
  tags: neutron

- name: disable neutron-openvswitch-agent
  service: name=neutron-openvswitch-agent enabled=no 
  when: use_neutron_ovs and use_ha_controller
  tags: neutron

- name: enable neutron services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
  when: use_neutron and not use_ha_controller
  tags: neutron

- name: enable neutron-openvswitch-agent
  service: name=neutron-openvswitch-agent enabled=yes state=started
  when: use_neutron_ovs and not use_ha_controller
  tags: neutron

- include: rhel7-icehouse-cluster-resources.yml
  when: openstack_release == 'icehouse' and ansible_distribution_major_version|int == 7
  tags: neutron

- include: rhel6-icehouse-cluster-resources.yml
  when: openstack_release == 'icehouse' and ansible_distribution_major_version|int == 6
  tags: neutron

- include: rhel6-havana-cluster-resources.yml
  when: openstack_release == 'havana' and ansible_distribution_major_version|int == 6
  tags: neutron

- include: cluster-constraints.yml
  tags: neutron
