---
- name: install mysql database packages
  yum: pkg=mysql-server state=present
  tags: mysql

- name: install auxiliary database packages
  yum: pkg={{ item }} state=present
  with_items:
    - MySQL-python
    - xinetd
    - nfs-utils
  tags: mysql

- name: deploy mysql server config file with increased number of max_connections
  copy: src=my.cnf dest=/etc/my.cnf mode=0644 owner=root group=root
  tags: mysql

- name: enable xinetd service
  service: name=xinetd enabled=yes state=started
  tags: mysql

- name: enable mysql service
  service: name=mysqld enabled=yes state=started
  tags: mysql

- name: create databases
  mysql_db: name={{ item }} state=present
  with_items:
    - keystone
    - glance
    - cinder
    - nova
    - neutron
    - heat
  run_once: true
  tags: mysql

- name: create keystone database users
  mysql_user: name={{ item.name }} host=% password={{ item.password }} priv={{ item.db }}.*:{{ item.priv }} state=present
  with_items:
    - { name: root, password: "{{ db_root_password }}", db: '*', priv: 'ALL,GRANT' }
    - { name: keystone, password: "{{ keystone_db_pass }}", db: keystone, priv: ALL }
    - { name: glance, password: "{{ glance_db_pass }}", db: glance, priv: ALL }
    - { name: cinder, password: "{{ cinder_db_pass }}", db: cinder, priv: ALL }
    - { name: nova, password: "{{ nova_db_pass }}", db: nova, priv: ALL }
    - { name: neutron, password: "{{ neutron_db_pass }}", db: neutron, priv: ALL }
    - { name: heat, password: "{{ heat_db_pass }}", db: heat, priv: ALL }
  run_once: true
  notify: flush db hosts
  tags: mysql
