---
- include: "RedHat-rpms.yml"
  when: ansible_os_family == "RedHat"
  tags: common

- name: enable ssh key-based access
  authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  notify: restore selinux context of .ssh files
  tags: sshkey

- name: set selinux policy and mode
  selinux: policy=targeted state=permissive
  tags: selinux

- name: install ntp
  yum: pkg=ntp state=installed
  tags: ntp

- name: configure ntp service
  template: src=ntp.conf.j2 dest=/etc/ntp.conf force=yes
  notify:
    - restart ntpd
  tags: ntp

- name: stop ntpd service to prepare for time synchronization
  service: name=ntpd state=stopped
  when: force_ntpdate == "yes"
  tags: ntp

- name: sync time from ntp servers
  command: ntpdate {{ ntp | join(" ") }}
  when: force_ntpdate == "yes"
  tags: ntp

- name: start ntpd service
  service: name=ntpd enabled=yes state=started
  tags: ntp

- name: deploy resolv.conf
  copy: src=files/resolv.conf dest=/etc/resolv.conf
  tags: dns
